language: elixir
elixir:
  - 1.8
env:
  - MIX_ENV=test
before_script:
  - npm install
  - node node_modules/.bin/jsonlint quotes.json
script:
  - mix coveralls.json
after_success:
  - bash <(curl -s https://codecov.io/bash)
