language: elixir
elixir:
  - 1.9
env:
  - MIX_ENV=test
before_install:
  - npm install # install jsonlint
  - npm run jsonlint # ensure that quotes.json is valid JSON
script:
  - mix coveralls.json
after_success:
  - bash <(curl -s https://codecov.io/bash)
